from django.db import models


class Tag(models.Model):
    """
    A Mmdia category tag generated by the user

    """

    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Media(models.Model):
    """
    One media file (audio, image, video, etc.)

    """

    MEDIA_TYPES = (
        ('IMG', 'Image'),
        ('AUD', 'Audio'),
        ('VID', 'Video'),
        ('Lnk', 'Link')
    )

    name = models.CharField(max_length=256)
    type = models.CharField(max_length=3, choices=MEDIA_TYPES)
    file = models.FileField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    is_published = models.NullBooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name='uploads')

    def __str__(self):
        return f"{self.name}, {self.type}"